-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 10:27:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema WebWareBo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WebWareBo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebWareBo` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema dbfirst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbfirst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbfirst` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `WebWareBo` ;

-- -----------------------------------------------------
-- Table `WebWareBo`.`sdg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebWareBo`.`sdg` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `image` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4;

USE `dbfirst` ;

-- -----------------------------------------------------
-- Table `dbfirst`.`film of serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfirst`.`film of serie` (
  `idfilm of serie` INT NOT NULL,
  `one piece` VARCHAR(45) NULL DEFAULT NULL,
  `fire force` VARCHAR(45) NULL DEFAULT NULL,
  `sword art online` VARCHAR(45) NULL DEFAULT NULL,
  `naruto` VARCHAR(45) NULL DEFAULT NULL,
  `bleach` VARCHAR(45) NULL DEFAULT NULL,
  `iron man` VARCHAR(45) NULL DEFAULT NULL,
  `thor: ragnarok` VARCHAR(45) NULL DEFAULT NULL,
  `five nights at freddys` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idfilm of serie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbfirst`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfirst`.`games` (
  `idgame` INT NOT NULL,
  `smash bros ultimate` VARCHAR(45) NULL DEFAULT NULL,
  `breath of the wild` VARCHAR(45) NULL DEFAULT NULL,
  `rainbow six siege` VARCHAR(45) NULL DEFAULT NULL,
  `subway surfers` VARCHAR(45) NULL DEFAULT NULL,
  `warframe` VARCHAR(45) NULL DEFAULT NULL,
  `splatoon` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idgame`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbfirst`.`muziek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfirst`.`muziek` (
  `idmuziek` INT NOT NULL,
  `armed and dangerous` VARCHAR(45) NULL DEFAULT NULL,
  `lucid dreams` VARCHAR(45) NULL DEFAULT NULL,
  `gotham` VARCHAR(45) NULL DEFAULT NULL,
  `ransom` VARCHAR(45) NULL DEFAULT NULL,
  `miss you` VARCHAR(45) NULL DEFAULT NULL,
  `black skinhead` VARCHAR(45) NULL DEFAULT NULL,
  `poker face` VARCHAR(45) NULL DEFAULT NULL,
  `homicide` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmuziek`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
